files:
  "/etc/nginx/conf.d/proxy.conf":
    mode: "000644"
    owner: root
    group: root
    content: |
      client_max_body_size 36M;

container_commands:
  01_reload_nginx:
    command: "if ! grep -q 'client_max_body_size 36M;' /etc/nginx/conf.d/proxy.conf; then sudo nginx -t && sudo systemctl reload nginx; fi"
    ignoreErrors: true
