package swari.sewa.module.subscription.enums;

public enum SubscriptionAction {
    PLAN_CREATED,
    PLAN_UPDATED,
    PLAN_PUBLISHED,
    PLAN_DISABLED,
    PLAN_ARCHIVED,
    PLAN_DUPLICATED,
    PLAN_DELETED,
    SUBSCRIPTION_CREATED,
    SUBSCRIPTION_UPGRADED,
    SUBSCRIPTION_DOWNGRADED,
    SUBSCRIPTION_SUSPENDED,
    SUBSCRIPTION_CANCELLED,
    PAYMENT_COMPLETED,
    PAYMENT_FAILED,
    COUPON_CREATED,
    COUPON_UPDATED,
    COUPON_DELETED,
    TRIAL_UPDATED,
    SETTINGS_UPDATED
}
